name: Bug Report
description: File a bug report to help us improve Moonflare
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your bug report.
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported already
          required: true
        - label: I have checked that I'm using the latest version of Moonflare
          required: true

  - type: input
    attributes:
      label: Moonflare Version
      description: What version of Moonflare are you running?
      placeholder: "e.g., v0.1.0"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux (x86_64)
        - Linux (ARM64)
        - Linux (other)
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Windows (x86_64)
        - Windows (ARM64)
        - Windows (other)
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current Behavior
      description: Describe what's actually happening (the bug)
      placeholder: A clear and concise description of the bug
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen
      placeholder: A clear and concise description of what you expected
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Run command `moonflare init test-project`
        2. Navigate to the project directory
        3. Run `moonflare add react frontend`
        4. See error...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Command Output
      description: If applicable, paste the full command output here
      placeholder: |
        $ moonflare init test-project
        Error: ...
      render: shell

  - type: textarea
    attributes:
      label: Project Structure
      description: If relevant, please share your project structure
      placeholder: |
        my-project/
        ├── apps/
        ├── sites/
        └── workers/
      render: text

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, logs, etc.)
      placeholder: Any additional information that might help us understand the issue better