name: Feature Request
description: Suggest a new feature or improvement for Moonflare
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible about what you'd like to see.

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your feature request.
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested already
          required: true
        - label: I have considered if this feature aligns with Moonflare's goals (Cloudflare-focused monorepo management)
          required: true

  - type: textarea
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve? What's the use case?
      placeholder: |
        Describe the problem or limitation you're experiencing that this feature would address.
        
        For example: "When working with multiple Cloudflare Workers, it's difficult to manage shared configuration..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        Describe your ideal solution. How would the feature work? What commands or options would be involved?
        
        For example: "I would like a command like `moonflare config sync` that..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternative Solutions
      description: Are there any alternative solutions or workarounds you've considered?
      placeholder: |
        Describe any alternative approaches you've thought about or are currently using to work around this limitation.

  - type: dropdown
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - Project Management (init, add, rename, etc.)
        - Build System (Moon integration, WASM handling)
        - Cloudflare Integration (deployment, configuration)
        - Developer Experience (CLI UX, output formatting)
        - Templates & Scaffolding
        - Testing & Quality Assurance
        - Documentation & Help
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here
      placeholder: |
        Any additional information that would help us understand your request:
        - Mock-ups or examples of how it would work
        - Links to similar features in other tools
        - Context about your workflow or project setup